/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CLASES.Empleados.Area;
import CONEXIONES.Conexiones;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Facuymayriver
 */
public class AddAreaCargo extends javax.swing.JDialog {

    static int ban, id = 0;
    static String veri = "Opciones";
    Connection con = Conexiones.Conexion();

    /**
     * Creates new form AddAreaCargo
     */
    public AddAreaCargo(JFrame ventanaPrincipal, int ban) {
        super(ventanaPrincipal, true);
        initComponents();
        this.setLocationRelativeTo(null);
        AddAreaCargo.ban = ban;
        area.setVisible(false);
        areat.setVisible(false);
        if (ban == 0) {
            Titulo.setText("Nueva área");
            desc1.setText("Nombre de área");
        } else {
            Titulo.setText("Nuevo cargo");
            desc1.setText("Nombre de cargo");
            area.setVisible(true);
            areat.setVisible(true);
            CLASES.Empleados.AreaComb(con, area);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        desc1 = new javax.swing.JLabel();
        area = new javax.swing.JComboBox<>();
        areat = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        accionfin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Titulo.setText("jLabel1");

        text1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text1KeyTyped(evt);
            }
        });

        desc1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        desc1.setText("jLabel1");

        area.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaActionPerformed(evt);
            }
        });

        areat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        areat.setText("Area:");

        volver.setBackground(new java.awt.Color(78, 247, 177));
        volver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        accionfin.setBackground(new java.awt.Color(78, 247, 177));
        accionfin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        accionfin.setText("Cargar");
        accionfin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionfinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(Titulo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(areat))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(volver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(accionfin, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(desc1))
                                .addGap(0, 62, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addGap(33, 33, 33)
                .addComponent(desc1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(areat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volver)
                    .addComponent(accionfin))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void accionfinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionfinActionPerformed
        String nomb = text1.getText();
        if (ban == 1) {
            if (!nomb.trim().isEmpty() && !veri.equals("Opciones")) {
                try {
                    CLASES.Empleados.AgregarCargo(con, nomb, id);
                    JOptionPane.showMessageDialog(null, "Cargao");
                    this.dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(AddAreaCargo.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "¡HAY CAMPOS VACIOS! Por favor, revise");
            }
        } else if (ban==0){
            if (!nomb.trim().isEmpty()) {
                try {
                    CLASES.Empleados.AgregarArea(con, nomb, id);
                    JOptionPane.showMessageDialog(null, "Cargao");
                    this.dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(AddAreaCargo.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "¡HAY CAMPOS VACIOS! Por favor, revise");
            }
        }

    }//GEN-LAST:event_accionfinActionPerformed

    private void areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaActionPerformed
        Object value = area.getSelectedItem();
        if (value instanceof Area) {
            Area dat = (Area) value;
            id = dat.getId();
            veri = dat.getNombre();
        }
    }//GEN-LAST:event_areaActionPerformed

    private void text1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text1KeyTyped
        char c = evt.getKeyChar();

        //Permitir teclas de control como Backspace, Delete, Enter, etc.
        if (Character.isISOControl(c)) {
            return;
        }

        //Solo permitir letras y espacios
        if (!Character.isLetter(c) && !Character.isWhitespace(c)) {
            getToolkit().beep();
            evt.consume();
        }

        String textoActual = text1.getText();
        int longitud = textoActual.length();

        //Evita que se repita mas de dos letras seguidas
        if (longitud >= 2) {
            char ultimo = textoActual.charAt(longitud - 1);
            char penultimo = textoActual.charAt(longitud - 2);

            if (ultimo == penultimo && penultimo == c) {
                getToolkit().beep();
                evt.consume(); // evita que se escriba
            }
        }
    }//GEN-LAST:event_text1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAreaCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAreaCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAreaCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAreaCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAreaCargo(null, ban).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton accionfin;
    private javax.swing.JComboBox<Area> area;
    private javax.swing.JLabel areat;
    private javax.swing.JLabel desc1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField text1;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
