/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CONEXIONES.Conexiones;
import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Facuymayriver
 */
public class AddDelVicTrip extends javax.swing.JDialog {

    static int ban;
    Connection con = Conexiones.Conexion();

    //Metodos para editar
    public class ModeloEditablePorFila extends DefaultTableModel {

        private final int editableRow = -1;
        private final int band;

        public ModeloEditablePorFila(Object[] columnNames, int rowCount, int band) {
            super(columnNames, rowCount);
            this.band = band;
        }

        @Override
        public boolean isCellEditable(int row, int column) {
            // Solo permitir editar la columna 1 (índice 1) y solo si band == 1
            return band == 1 && column == 1;
        }

    }
    //Metodos para editar
    ModeloEditablePorFila tabla1 = new ModeloEditablePorFila(new String[]{"Nº", "Tripulación", "Victor"}, 0, ban);
    ModeloEditablePorFila tabla2 = new ModeloEditablePorFila(new String[]{"Nº", "Victor", "Patente"}, 0, ban);

    public AddDelVicTrip(JFrame ventanaPrincipal, int ban) {
        super(ventanaPrincipal, true);
        initComponents();
        this.setLocationRelativeTo(null);
        AddDelVicTrip.ban = ban;
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        Tabla.setDefaultRenderer(Object.class, centerRenderer);

        if (ban == 0) {
            Titulo.setText("Eliminar victor");
            Descripcion.setText("Seleccione un victor y presione el botón para eliminar");
            Tabla.setModel(tabla2);
            CLASES.Movimientos.tablaVic(con, tabla2);
            Tabla.getColumnModel().getColumn(0).setMinWidth(50);
            Tabla.getColumnModel().getColumn(0).setMaxWidth(50);

            Tabla.getColumnModel().getColumn(2).setMinWidth(310);
            Tabla.getColumnModel().getColumn(2).setMaxWidth(319);

        } else {
            Titulo.setText("Eliminar tripulación");
            Descripcion.setText("Seleccione un tripulación y presione el botón para eliminar");
            Tabla.setModel(tabla1);
            CLASES.Movimientos.tablaTrip(con, tabla1);
            Tabla.getColumnModel().getColumn(0).setMinWidth(50);
            Tabla.getColumnModel().getColumn(0).setMaxWidth(50);

            Tabla.getColumnModel().getColumn(1).setMinWidth(310);
            Tabla.getColumnModel().getColumn(1).setMaxWidth(310);

        }
        Tabla.setRowHeight(30);
        Tabla.getTableHeader().setReorderingAllowed(false);
        Tabla.getTableHeader().setResizingAllowed(false);
        
        int ventanaTheme = CLASES.MenuClass.VentanaOpcThemeRet();
            if (ventanaTheme == 0) {
            } else if (ventanaTheme == 1) {
                Color colorPersonalizado = new Color(44, 44, 53);
                Fondo.setBackground(colorPersonalizado);
                Titulo.setForeground(Color.WHITE);
                Descripcion.setForeground(Color.WHITE);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Eliminar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla);

        Eliminar.setBackground(new java.awt.Color(78, 247, 177));
        Eliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        volver.setBackground(new java.awt.Color(78, 247, 177));
        volver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        Titulo.setText("jLabel1");

        Descripcion.setText("jLabel1");

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(FondoLayout.createSequentialGroup()
                                .addComponent(volver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FondoLayout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(Titulo))
                            .addGroup(FondoLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(Descripcion)))
                        .addGap(0, 211, Short.MAX_VALUE)))
                .addContainerGap())
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(Descripcion)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eliminar)
                    .addComponent(volver))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        if (ban == 0) {
            int filaSeleccionada = Tabla.getSelectedRow();
            if (filaSeleccionada != -1) {
                int opcion = JOptionPane.showConfirmDialog(
                        null,
                        "¿Deseás Eliminar el victor?",
                        "Confirmar acción",
                        JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE
                );

                if (opcion == JOptionPane.OK_OPTION) {
                    int fila = Tabla.getSelectedRow();
                    int cod = Integer.parseInt(Tabla.getValueAt(fila, 0).toString());
                    try {
                        int veri = CLASES.Movimientos.ValidacionVic(con, cod);
                        switch (veri) {
                            case 1:
                                try {
                                    CLASES.Movimientos.EliminarVic(con, cod);
                                    JOptionPane.showMessageDialog(null, "Eliminao");
                                    tabla2.setRowCount(0);
                                    CLASES.Movimientos.tablaVic(con, tabla2);
                                    Tabla.setModel(tabla2);
                                } catch (SQLException ex) {
                                    JOptionPane.showMessageDialog(null, "ERROR" + ex);
                                }
                                break;
                            case 0:
                                try {
                                    CLASES.Movimientos.EliminarVic(con, cod);
                                    JOptionPane.showMessageDialog(null, "Eliminao");
                                    tabla2.setRowCount(0);
                                    CLASES.Movimientos.tablaVic(con, tabla2);
                                    Tabla.setModel(tabla2);
                                } catch (SQLException ex) {
                                    JOptionPane.showMessageDialog(null, "ERROR" + ex);
                                }
                                break;
                            case 2:
                                break;
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "ERROR" + ex);
                    }
                } else if (opcion == JOptionPane.CANCEL_OPTION || opcion == JOptionPane.CLOSED_OPTION) {
                    // El usuario eligió "Cancelar" o cerró la ventana
                    System.out.println("Cancelado");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una fila primero.");
            }
        } else if (ban == 1) {
            int filaSeleccionada = Tabla.getSelectedRow();
            if (filaSeleccionada != -1) {
                int opcion = JOptionPane.showConfirmDialog(
                        null,
                        "¿Deseás Eliminar la tripulación?",
                        "Confirmar acción",
                        JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE
                );

                if (opcion == JOptionPane.OK_OPTION) {
                    int fila = Tabla.getSelectedRow();
                    int cod = Integer.parseInt(Tabla.getValueAt(fila, 0).toString());
                    try {
                        CLASES.Movimientos.EliminarTrip(con, cod);
                        JOptionPane.showMessageDialog(null, "Eliminao");
                        tabla1.setRowCount(0);
                        CLASES.Movimientos.tablaTrip(con, tabla1);
                        Tabla.setModel(tabla1);
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "ERROR" + ex);
                    }
                } else if (opcion == JOptionPane.CANCEL_OPTION || opcion == JOptionPane.CLOSED_OPTION) {
                    // El usuario eligió "Cancelar" o cerró la ventana
                    System.out.println("Cancelado");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una fila primero.");
            }
        }
    }//GEN-LAST:event_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDelVicTrip.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDelVicTrip.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDelVicTrip.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDelVicTrip.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDelVicTrip(null, ban).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descripcion;
    private javax.swing.JButton Eliminar;
    private javax.swing.JPanel Fondo;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel Titulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
