/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CLASES.Movimientos.Cliente;
import CLASES.Movimientos.Trip;
import CONEXIONES.Conexiones;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class AddTri extends javax.swing.JDialog {

    Connection con = Conexiones.Conexion();
    ResultSet rs;
    int idChofer, idMedico, idEnfermero, idvictor, idtrip, iduser;
    static int idband;
    String fechaActual, veri;

    public AddTri(int idband, JFrame ventanaPrincipal) {
        super(ventanaPrincipal, true);
        AddTri.idband = idband;
        initComponents();
        this.setLocationRelativeTo(null);
        LocalDate hoy = LocalDate.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        fechaActual = hoy.format(formato);

        iduser = CLASES.Usuario.iduser();

        fechaActual = hoy.format(formato);
        if (idband == 0) {
            tripla.setVisible(false);
            Tripulacion.setVisible(false);
            CLASES.Movimientos.jChofer(con, ChoferCB, EnfermeroCB, MedicoCB, victor, idband);
        } else {
            carga.setText("Actualizar");
            CLASES.Movimientos.Select(con, Tripulacion, fechaActual);
            ChoferCB.setEnabled(false);
            EnfermeroCB.setEnabled(false);
            MedicoCB.setEnabled(false);
            victor.setEnabled(false);
            CLASES.Movimientos.jChofer(con, ChoferCB, EnfermeroCB, MedicoCB, victor, idband);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        carga = new javax.swing.JButton();
        Chofer = new javax.swing.JLabel();
        Enfermero = new javax.swing.JLabel();
        Medico = new javax.swing.JLabel();
        ChoferCB = new javax.swing.JComboBox<Cliente>();
        EnfermeroCB = new javax.swing.JComboBox<>();
        MedicoCB = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        victor = new javax.swing.JComboBox<>();
        Tripulacion = new javax.swing.JComboBox<>();
        tripla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(522, 240));
        setMinimumSize(new java.awt.Dimension(522, 240));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(522, 240));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Titulo.setText("Tripulación");

        Volver.setBackground(new java.awt.Color(78, 247, 177));
        Volver.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Volver.setText("Volver");
        Volver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        carga.setBackground(new java.awt.Color(78, 247, 177));
        carga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        carga.setText("Cargar");
        carga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaActionPerformed(evt);
            }
        });

        Chofer.setText("Chofer");

        Enfermero.setText("Enfermero");

        Medico.setText("Medico");

        jLabel1.setText("Victor");

        Tripulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TripulacionActionPerformed(evt);
            }
        });

        tripla.setText("Tripulación");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(Titulo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ChoferCB, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Chofer))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Enfermero)
                                            .addComponent(EnfermeroCB, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Medico)
                                            .addComponent(MedicoCB, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(victor, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1)
                                            .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tripla)
                                            .addComponent(Tripulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(carga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Chofer)
                    .addComponent(Enfermero)
                    .addComponent(Medico))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChoferCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnfermeroCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MedicoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tripla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tripulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(victor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carga, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void cargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaActionPerformed
        Object value = ChoferCB.getSelectedItem();
        if (value instanceof Cliente) {
            Cliente cli = (Cliente) value;
            idChofer = cli.getId();
        }

        Object value2 = EnfermeroCB.getSelectedItem();
        if (value2 instanceof Cliente) {
            Cliente cli = (Cliente) value2;
            idEnfermero = cli.getId();
        }

        Object value3 = MedicoCB.getSelectedItem();
        if (value3 instanceof Cliente) {
            Cliente cli = (Cliente) value3;
            idMedico = cli.getId();
        }

        Object value4 = victor.getSelectedItem();
        if (value4 instanceof Cliente) {
            Cliente cli = (Cliente) value4;
            idvictor = cli.getId();
        }

        if (idband == 0) {
            try {
                CLASES.Movimientos.Carga(con, idChofer, idEnfermero, idMedico, idvictor, fechaActual, iduser);
                this.dispose();
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(null, "ERROR1");
            } catch (SQLException ex) {
                Logger.getLogger(AddTri.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            int opcion = JOptionPane.showConfirmDialog(
                    null,
                    "¿Deseás Actualizar?",
                    "Confirmar acción",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE
            );

            if (opcion == JOptionPane.OK_OPTION) {
                try {
                    CLASES.Movimientos.ActualizarTrip(con, idChofer, idEnfermero, idMedico, idvictor, idtrip, iduser);
                    JOptionPane.showMessageDialog(null, "Cargao");
                    this.dispose();
                } catch (HeadlessException e) {
                    JOptionPane.showMessageDialog(null, "ERROR1");
                }
            }
        }
    }//GEN-LAST:event_cargaActionPerformed

    private void TripulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TripulacionActionPerformed
        Object value = Tripulacion.getSelectedItem();
        if (value instanceof Trip) {
            Trip dat = (Trip) value;
            idtrip = dat.getId();
            veri = dat.getNombre();

            if (!veri.equals("Opciones")) {
                try {
                    ChoferCB.setEnabled(true);
                    EnfermeroCB.setEnabled(true);
                    MedicoCB.setEnabled(true);
                    victor.setEnabled(true);
                    CLASES.Movimientos.EditarTrip(con, idtrip, ChoferCB, EnfermeroCB, MedicoCB, victor);

                } catch (HeadlessException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            } else {
                ChoferCB.setEnabled(false);
                EnfermeroCB.setEnabled(false);
                MedicoCB.setEnabled(false);
                victor.setEnabled(false);
            }
        }
    }//GEN-LAST:event_TripulacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTri(idband, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Chofer;
    private javax.swing.JComboBox<Cliente> ChoferCB;
    private javax.swing.JLabel Enfermero;
    private javax.swing.JComboBox<Cliente> EnfermeroCB;
    private javax.swing.JLabel Medico;
    private javax.swing.JComboBox<Cliente> MedicoCB;
    private javax.swing.JLabel Titulo;
    private javax.swing.JComboBox<Trip> Tripulacion;
    private javax.swing.JButton Volver;
    private javax.swing.JButton carga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel tripla;
    private javax.swing.JComboBox<Cliente> victor;
    // End of variables declaration//GEN-END:variables
}
