/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import java.sql.Connection;
import java.sql.ResultSet;
import CONEXIONES.Conexiones;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Facuymayriver
 */
public class Empleados extends javax.swing.JFrame {

    public int x = 0, c = 0, id;
    Connection con = Conexiones.Conexion();
    ResultSet rs;
    int cont = 0;

    public void refrescarTablaEmpleados() {
        tabla1.setRowCount(0); // Limpia
        try {
            CLASES.Empleados.MostrarEmpleados(con, tabla1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al refrescar categorías");
        }
    }

    public void refrescarCombo() {
        while (Cargo.getItemCount() > 1) {
            Cargo.removeItemAt(1); // Siempre elimina el segundo, el resto se va corriendo
        }
        CLASES.Empleados.ActjCombo(con, Cargo);
    }

    //Metodos para editar
    public class ModeloEditablePorFila extends DefaultTableModel {

        private int editableRow = -1;

        public ModeloEditablePorFila(Object[] columnNames, int rowCount) {
            super(columnNames, rowCount);
        }

        @Override
        public boolean isCellEditable(int row, int column) {
            if (column == 0) {
                return false; // Nunca editar la columna ID
            }
            Object cod = getValueAt(row, 0);

            // Si es una fila nueva → editable
            if (cod == null || cod.toString().trim().isEmpty()) {
                return true;
            }

            // Si estamos en modo edición manual → solo esa fila
            return row == editableRow;
        }

        public void setEditableRow(int row) {
            this.editableRow = row;
            fireTableRowsUpdated(row, row);
        }

        public void bloquearEdicion() {
            this.editableRow = -1;
            fireTableDataChanged();
        }
    }
    //Metodos para editar

    //Tabla
    ModeloEditablePorFila tabla1 = new ModeloEditablePorFila(new String[]{"Cod", "Nombre", "Apellido", "DNI", "Telefono", "Cargo"}, 0) {
        private final int editableRow = -1;
    };
    //Tabla

    public Empleados() {
        initComponents();
        this.setLocationRelativeTo(null);

        Nombre.setEnabled(false);
        Apellido.setEnabled(false);
        DNI.setEnabled(false);
        Domicilio.setEnabled(false);
        Email.setEnabled(false);
        Telefono.setEnabled(false);
        Fecha.setEnabled(false);
        GS.setEnabled(false);
        Cargo.setEnabled(false);
        nuevocargo.setEnabled(false);
        GuardarCargo.setEnabled(false);
        Limpiar.setEnabled(false);
        Guardar.setEnabled(false);
        area.setEnabled(false);

        Cargar.setText("Cargar");

        CLASES.Empleados.jCombo(con, GS, Cargo, area);

        Tabla.setModel(tabla1);
        Tabla.setRowHeight(30);
        
        Tabla.getTableHeader().setReorderingAllowed(false);
        
        Tabla.getColumnModel().getColumn(0).setMinWidth(40);
        Tabla.getColumnModel().getColumn(0).setMaxWidth(40);

        Tabla.getColumnModel().getColumn(1).setMinWidth(80);
        Tabla.getColumnModel().getColumn(1).setMaxWidth(80);

        Tabla.getColumnModel().getColumn(2).setMinWidth(70);
        Tabla.getColumnModel().getColumn(2).setMaxWidth(70);
        
        Tabla.getColumnModel().getColumn(3).setMinWidth(100);
        Tabla.getColumnModel().getColumn(3).setMaxWidth(100);
        
        Tabla.getColumnModel().getColumn(4).setMinWidth(100);
        Tabla.getColumnModel().getColumn(4).setMaxWidth(100);

        //Mostrar tabla
        try {
            CLASES.Empleados.MostrarEmpleados(con, tabla1);
            if (Tabla.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "No se encontró ningún Cliente.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Menu = new javax.swing.JButton();
        Movimiento = new javax.swing.JButton();
        Asistencia = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Empleados = new javax.swing.JButton();
        Estadisticas = new javax.swing.JButton();
        Ayuda = new javax.swing.JButton();
        Configuracion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        Email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        DNI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        GS = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Cargo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        Telefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Domicilio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        Apellido = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        Fecha = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jSeparator9 = new javax.swing.JSeparator();
        Cargar = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        NewCargo = new javax.swing.JCheckBox();
        nuevocargo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        opcCargo = new javax.swing.JComboBox<>();
        GuardarCargo = new javax.swing.JButton();
        area = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        Opciones2 = new javax.swing.JMenu();
        Menu2 = new javax.swing.JMenuItem();
        Movimientos = new javax.swing.JMenuItem();
        Asistencia2 = new javax.swing.JMenuItem();
        Empleados2 = new javax.swing.JMenuItem();
        Estadisticas2 = new javax.swing.JMenuItem();
        Ayuda2 = new javax.swing.JMenuItem();
        Configuracion2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Empleados");
        setName("Empleados"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.setForeground(new java.awt.Color(153, 153, 0));

        Menu.setBackground(new java.awt.Color(0, 102, 0));
        Menu.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        Menu.setForeground(new java.awt.Color(255, 255, 255));
        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/menui.png"))); // NOI18N
        Menu.setText("Menu");
        Menu.setToolTipText("ir al menu");
        Menu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Menu.setBorderPainted(false);
        Menu.setContentAreaFilled(false);
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu.setDefaultCapable(false);
        Menu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/menui2.png"))); // NOI18N
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        Movimiento.setBackground(new java.awt.Color(0, 102, 0));
        Movimiento.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        Movimiento.setForeground(new java.awt.Color(255, 255, 255));
        Movimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/movimiento.png"))); // NOI18N
        Movimiento.setText("Movimientos");
        Movimiento.setToolTipText("ir a movimientos");
        Movimiento.setBorderPainted(false);
        Movimiento.setContentAreaFilled(false);
        Movimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Movimiento.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/movimiento2.png"))); // NOI18N
        Movimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimientoActionPerformed(evt);
            }
        });

        Asistencia.setBackground(new java.awt.Color(0, 102, 0));
        Asistencia.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        Asistencia.setForeground(new java.awt.Color(255, 255, 255));
        Asistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/asistencia.png"))); // NOI18N
        Asistencia.setText("Asistencia");
        Asistencia.setToolTipText("ir a asistencia");
        Asistencia.setBorderPainted(false);
        Asistencia.setContentAreaFilled(false);
        Asistencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Asistencia.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/asistencia2.png"))); // NOI18N
        Asistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsistenciaActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(0, 102, 0));
        Salir.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/salir.png"))); // NOI18N
        Salir.setText("Salir");
        Salir.setToolTipText("Salir del programa");
        Salir.setBorderPainted(false);
        Salir.setContentAreaFilled(false);
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/salir2.png"))); // NOI18N
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Empleados.setBackground(new java.awt.Color(0, 102, 0));
        Empleados.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        Empleados.setForeground(new java.awt.Color(255, 255, 255));
        Empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/empleado.png"))); // NOI18N
        Empleados.setText("Empleados");
        Empleados.setToolTipText("ir a empleados");
        Empleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Empleados.setContentAreaFilled(false);
        Empleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Empleados.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/empleado2.png"))); // NOI18N
        Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadosActionPerformed(evt);
            }
        });

        Estadisticas.setBackground(new java.awt.Color(0, 102, 0));
        Estadisticas.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        Estadisticas.setForeground(new java.awt.Color(255, 255, 255));
        Estadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/estats.png"))); // NOI18N
        Estadisticas.setText("Estadisticas");
        Estadisticas.setToolTipText("ir a estadisticas");
        Estadisticas.setBorderPainted(false);
        Estadisticas.setContentAreaFilled(false);
        Estadisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Estadisticas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/estats2.png"))); // NOI18N
        Estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadisticasActionPerformed(evt);
            }
        });

        Ayuda.setBackground(new java.awt.Color(0, 102, 0));
        Ayuda.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        Ayuda.setForeground(new java.awt.Color(255, 255, 255));
        Ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ayuda.png"))); // NOI18N
        Ayuda.setText("Ayuda");
        Ayuda.setToolTipText("ir a ayuda");
        Ayuda.setBorderPainted(false);
        Ayuda.setContentAreaFilled(false);
        Ayuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ayuda.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ayuda2.png"))); // NOI18N
        Ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaActionPerformed(evt);
            }
        });

        Configuracion.setBackground(new java.awt.Color(0, 102, 0));
        Configuracion.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        Configuracion.setForeground(new java.awt.Color(255, 255, 255));
        Configuracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/config.png"))); // NOI18N
        Configuracion.setText("Configuración");
        Configuracion.setToolTipText("ir a configuración");
        Configuracion.setBorderPainted(false);
        Configuracion.setContentAreaFilled(false);
        Configuracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Configuracion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/config2.png"))); // NOI18N
        Configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfiguracionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Movimiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Asistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Estadisticas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ayuda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Configuracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(Salir))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Movimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Menu)
                .addComponent(Asistencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Empleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Estadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Ayuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Salir)
                .addComponent(Configuracion))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(153, 255, 204));

        jPanel4.setBackground(new java.awt.Color(157, 157, 190));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 530, 20));
        jPanel4.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 530, 20));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText(">Fecha de Nacimiento:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));
        jPanel5.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 210, 20));

        Email.setBorder(null);
        jPanel5.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 210, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText(">Email:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        jPanel5.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 210, 20));

        DNI.setBorder(null);
        DNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNIActionPerformed(evt);
            }
        });
        DNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DNIKeyTyped(evt);
            }
        });
        jPanel5.add(DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 200, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText(">DNI:");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        jPanel5.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, 20));

        GS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opciones" }));
        GS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(GS, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 110, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText(">Grupo sanguineo:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        Cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opciones" }));
        Cargo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(Cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 100, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText(">Cargo:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));

        Telefono.setBorder(null);
        Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoKeyTyped(evt);
            }
        });
        jPanel5.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 210, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText(">Telefono:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 230, 20));

        Domicilio.setBorder(null);
        Domicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DomicilioKeyTyped(evt);
            }
        });
        jPanel5.add(Domicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 222, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText(">Domicilio:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));
        jPanel5.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 190, 20));

        Apellido.setBorder(null);
        Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoActionPerformed(evt);
            }
        });
        Apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ApellidoKeyTyped(evt);
            }
        });
        jPanel5.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 180, 20));

        Nombre.setBorder(null);
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreKeyTyped(evt);
            }
        });
        jPanel5.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText(">Nombres:");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText(">Apellido:");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));
        jPanel5.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 210, 20));
        jPanel5.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 220, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 530, 320));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel6.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 30, 90));

        Cargar.setText("boton");
        Cargar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarActionPerformed(evt);
            }
        });
        jPanel6.add(Cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        Limpiar.setText("Limpiar");
        Limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        jPanel6.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 80, -1));

        Guardar.setText("Guardar");
        Guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel6.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Opciones");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Opciones de cargo:");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, 20));

        NewCargo.setBackground(new java.awt.Color(255, 255, 255));
        NewCargo.setText("Nuevo cargo");
        NewCargo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NewCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCargoActionPerformed(evt);
            }
        });
        jPanel6.add(NewCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        nuevocargo.setBorder(null);
        nuevocargo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nuevocargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevocargoActionPerformed(evt);
            }
        });
        jPanel6.add(nuevocargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 140, 20));
        jPanel6.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 140, 20));

        opcCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opciones", "Modificar", "Eliminar" }));
        opcCargo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opcCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcCargoActionPerformed(evt);
            }
        });
        jPanel6.add(opcCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 120, -1));

        GuardarCargo.setText("Guardar");
        GuardarCargo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GuardarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarCargoActionPerformed(evt);
            }
        });
        jPanel6.add(GuardarCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        area.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Area" }));
        jPanel6.add(area, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 120, -1));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 530, 110));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cargar nuevo empleado");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 170, 30));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 300, 30));

        jPanel9.setBackground(new java.awt.Color(157, 157, 190));
        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Cargo"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 504, 420));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Tabla de empleados");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, 30));

        jPanel9.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 11, 331, 30));

        Modificar.setText("Modificar");
        Modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jPanel9.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 100, 30));

        Eliminar.setText("Eliminar");
        Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel9.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 101, 27));
        jPanel9.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 46, 504, 10));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        Opciones2.setText("Opciones");
        Opciones2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Menu2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        Menu2.setText("Menu");
        Menu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu2ActionPerformed(evt);
            }
        });
        Opciones2.add(Menu2);

        Movimientos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        Movimientos.setText("Movimientos");
        Movimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimientosActionPerformed(evt);
            }
        });
        Opciones2.add(Movimientos);

        Asistencia2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        Asistencia2.setText("Asistencia");
        Asistencia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Asistencia2ActionPerformed(evt);
            }
        });
        Opciones2.add(Asistencia2);

        Empleados2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        Empleados2.setText("Empleados");
        Empleados2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Empleados2ActionPerformed(evt);
            }
        });
        Opciones2.add(Empleados2);

        Estadisticas2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        Estadisticas2.setText("Estadisticas");
        Estadisticas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Estadisticas2ActionPerformed(evt);
            }
        });
        Opciones2.add(Estadisticas2);

        Ayuda2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        Ayuda2.setText("Ayuda");
        Ayuda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ayuda2ActionPerformed(evt);
            }
        });
        Opciones2.add(Ayuda2);

        Configuracion2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        Configuracion2.setText("Configuracion");
        Configuracion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Configuracion2ActionPerformed(evt);
            }
        });
        Opciones2.add(Configuracion2);

        jMenuBar1.add(Opciones2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadisticasActionPerformed
        Estadisticas ventana = new Estadisticas();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EstadisticasActionPerformed

    private void AsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsistenciaActionPerformed
        Asistencia ventana = new Asistencia();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AsistenciaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void ConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfiguracionActionPerformed
        Configuracion ventana = new Configuracion();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ConfiguracionActionPerformed

    private void MovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimientoActionPerformed
        Movimiento ventana = new Movimiento();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MovimientoActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        Menu ventana = new Menu();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuActionPerformed

    private void EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadosActionPerformed

    }//GEN-LAST:event_EmpleadosActionPerformed

    private void AyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaActionPerformed
        Ayuda ventana = new Ayuda();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AyudaActionPerformed

    private void Menu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu2ActionPerformed
        Menu ventana = new Menu();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Menu2ActionPerformed

    private void MovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimientosActionPerformed
        Movimiento ventana = new Movimiento();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MovimientosActionPerformed

    private void Asistencia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Asistencia2ActionPerformed
        Asistencia ventana = new Asistencia();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Asistencia2ActionPerformed

    private void Empleados2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Empleados2ActionPerformed

    }//GEN-LAST:event_Empleados2ActionPerformed

    private void Estadisticas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Estadisticas2ActionPerformed
        Estadisticas ventana = new Estadisticas();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Estadisticas2ActionPerformed

    private void Ayuda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ayuda2ActionPerformed
        Ayuda ventana = new Ayuda();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ayuda2ActionPerformed

    private void Configuracion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Configuracion2ActionPerformed
        Configuracion ventana = new Configuracion();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Configuracion2ActionPerformed

    private void DNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNIActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoActionPerformed

    private void CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarActionPerformed
        c = 0;
        if (x == 0) {
            x = 1;
            Nombre.setEnabled(true);
            Apellido.setEnabled(true);
            DNI.setEnabled(true);
            Domicilio.setEnabled(true);
            Email.setEnabled(true);
            Telefono.setEnabled(true);
            Fecha.setEnabled(true);
            Limpiar.setEnabled(true);
            Guardar.setEnabled(true);
            GS.setEnabled(true);
            Cargo.setEnabled(true);
            NewCargo.setEnabled(false);
            opcCargo.setEnabled(false);
            Eliminar.setEnabled(false);
            Modificar.setEnabled(false);

            Menu.setEnabled(false);
            Movimiento.setEnabled(false);
            Asistencia.setEnabled(false);
            Empleados.setEnabled(false);
            Estadisticas.setEnabled(false);
            Ayuda.setEnabled(false);
            Configuracion.setEnabled(false);
            Salir.setEnabled(false);

            Cargar.setText("Cancelar");
        } else if (x == 1) {
            Nombre.setEnabled(false);
            Apellido.setEnabled(false);
            DNI.setEnabled(false);
            Domicilio.setEnabled(false);
            Email.setEnabled(false);
            Telefono.setEnabled(false);
            Fecha.setEnabled(false);
            GS.setEnabled(false);
            Cargo.setEnabled(false);
            NewCargo.setEnabled(true);
            GuardarCargo.setEnabled(false);
            Limpiar.setEnabled(false);
            Guardar.setEnabled(false);
            opcCargo.setEnabled(true);
            Eliminar.setEnabled(true);
            Modificar.setEnabled(true);

            Menu.setEnabled(true);
            Movimiento.setEnabled(true);
            Asistencia.setEnabled(true);
            Empleados.setEnabled(true);
            Estadisticas.setEnabled(true);
            Ayuda.setEnabled(true);
            Configuracion.setEnabled(true);
            Salir.setEnabled(true);

            Nombre.setText("");
            Apellido.setText("");
            DNI.setText("");
            Domicilio.setText("");
            Email.setText("");
            Telefono.setText("");
            GS.setSelectedIndex(0);
            Cargo.setSelectedIndex(0);
            Fecha.setDate(null);

            Cargar.setText("Cargar");
            x = 0;
        }
    }//GEN-LAST:event_CargarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        Nombre.setText("");
        Apellido.setText("");
        DNI.setText("");
        Domicilio.setText("");
        Email.setText("");
        Telefono.setText("");
        GS.setSelectedIndex(0);
        Cargo.setSelectedIndex(0);
        Fecha.setDate(null);
    }//GEN-LAST:event_LimpiarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        if (c == 0) {
            String nomb = Nombre.getText();
            String ap = Apellido.getText();
            String dni = DNI.getText();
            String dom = Domicilio.getText();
            String em = Email.getText();
            String tel = Telefono.getText();

            Date fecha1 = Fecha.getDate();
            if (fecha1 == null) {
                JOptionPane.showMessageDialog(null, "¡HAY CAMPOS VACIOS! Por favor, revise");
                return;
            }
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String fe = sdf.format(fecha1);

            String gs = (String) GS.getSelectedItem();
            String car = (String) Cargo.getSelectedItem();
            if (!nomb.trim().isEmpty() && !ap.trim().isEmpty() && !dni.trim().isEmpty() && !dom.trim().isEmpty() && !em.trim().isEmpty() && !tel.trim().isEmpty() && !gs.equals("Opciones") && !car.equals("Opciones")) {
                if (em.contains("@") && em.contains(".")) {
                    try {
                        CLASES.Empleados.AgregarEmpleados(con, nomb, ap, dni, dom, em, tel, fe, gs, car);
                        JOptionPane.showMessageDialog(null, "Guardado");
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "ERROR1");
                    }

                    try {
                        tabla1.setRowCount(0); // Limpia
                        CLASES.Empleados.MostrarEmpleados(con, tabla1);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Error al refrescar categorías");
                    }

                    Nombre.setText("");
                    Apellido.setText("");
                    DNI.setText("");
                    Domicilio.setText("");
                    Email.setText("");
                    Telefono.setText("");
                    GS.setSelectedIndex(0);
                    Cargo.setSelectedIndex(0);
                    Fecha.setDate(null);
                } else {
                    JOptionPane.showMessageDialog(null, "Introduzca un correo valido!");
                }

            } else {
                JOptionPane.showMessageDialog(null, "¡HAY CAMPOS VACIOS! Por favor, revise");
            }

        } else if (c == 1) {
            String nomb = Nombre.getText();
            String ap = Apellido.getText();
            String dni = DNI.getText();
            String dom = Domicilio.getText();
            String em = Email.getText();
            String tel = Telefono.getText();

            Date fecha1 = Fecha.getDate();
            if (fecha1 == null) {
                JOptionPane.showMessageDialog(null, "¡HAY CAMPOS VACIOS! Por favor, revise");
                return;
            }
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // Puedes cambiar el formato según lo necesites
            String fe = sdf.format(fecha1);

            String gs = (String) GS.getSelectedItem();
            String car = (String) Cargo.getSelectedItem();

            if (!nomb.trim().isEmpty() && !ap.trim().isEmpty() && !dni.trim().isEmpty() && !dom.trim().isEmpty() && !em.trim().isEmpty() && !tel.trim().isEmpty() && !gs.equals("Opciones") && !car.equals("Opciones")) {
                if (em.contains("@") && em.contains(".")) {
                    try {
                        CLASES.Empleados.ModificarEmpleados(con, id, nomb, ap, dni, dom, em, tel, fe, gs, car);
                        JOptionPane.showMessageDialog(null, "Actualizado");
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "ERROR1");
                    }

                    try {
                        tabla1.setRowCount(0); // Limpia
                        CLASES.Empleados.MostrarEmpleados(con, tabla1);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Error al refrescar categorías");
                    }
                    Nombre.setText("");
                    Apellido.setText("");
                    DNI.setText("");
                    Domicilio.setText("");
                    Email.setText("");
                    Telefono.setText("");

                    Nombre.setEnabled(false);
                    Apellido.setEnabled(false);
                    DNI.setEnabled(false);
                    Domicilio.setEnabled(false);
                    Email.setEnabled(false);
                    Telefono.setEnabled(false);
                    Fecha.setEnabled(false);
                    GS.setEnabled(false);
                    Cargo.setEnabled(false);
                    NewCargo.setEnabled(true);
                    GuardarCargo.setEnabled(false);
                    Limpiar.setEnabled(false);
                    Guardar.setEnabled(false);
                    opcCargo.setEnabled(true);
                    Eliminar.setEnabled(true);
                    Modificar.setEnabled(true);

                    Menu.setEnabled(true);
                    Movimiento.setEnabled(true);
                    Asistencia.setEnabled(true);
                    Empleados.setEnabled(true);
                    Estadisticas.setEnabled(true);
                    Ayuda.setEnabled(true);
                    Configuracion.setEnabled(true);
                    Salir.setEnabled(true);
                    Cargar.setText("Cargar");
                    GS.setSelectedIndex(0);
                    Cargo.setSelectedIndex(0);
                    Fecha.setDate(null);
                    x = 0;
                } else {
                    JOptionPane.showMessageDialog(null, "Introduzca un correo valido!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "¡HAY CAMPOS VACIOS! Por favor, revise");
            }
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyTyped
        char c = evt.getKeyChar();

        //Permitir teclas de control como Backspace, Delete, Enter, etc.
        if (Character.isISOControl(c)) {
            return;
        }

        //Solo permitir letras y espacios
        if (!Character.isLetter(c) && !Character.isWhitespace(c)) {
            getToolkit().beep();
            evt.consume();
        }

        String textoActual = Nombre.getText();
        int longitud = textoActual.length();

        //Evita que se repita mas de dos letras seguidas
        if (longitud >= 2) {
            char ultimo = textoActual.charAt(longitud - 1);
            char penultimo = textoActual.charAt(longitud - 2);

            if (ultimo == penultimo && penultimo == c) {
                getToolkit().beep();
                evt.consume(); // evita que se escriba
            }
        }
    }//GEN-LAST:event_NombreKeyTyped

    private void ApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApellidoKeyTyped
        char e = evt.getKeyChar();

        //Permitir teclas de control como Backspace, Delete, Enter, etc.
        if (Character.isISOControl(e)) {
            return;
        }

        //Solo permitir letras y espacios
        if (!Character.isLetter(e) && !Character.isWhitespace(e)) {
            getToolkit().beep();
            evt.consume();
            return;
        }

        String textoActual = Apellido.getText();
        int longitud = textoActual.length();

        if (longitud >= 2) {
            char ultimo = textoActual.charAt(longitud - 1);
            char penultimo = textoActual.charAt(longitud - 2);

            if (ultimo == penultimo && penultimo == e) {
                getToolkit().beep();
                evt.consume(); // evita que se escriba
            }
        }
    }//GEN-LAST:event_ApellidoKeyTyped

    private void DNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DNIKeyTyped
        char r = evt.getKeyChar();

        if (Character.isISOControl(r)) {
            return; // permite borrar, mover, etc.
        }

        //Solo permite letras, numeros y signos no
        if (!Character.isDigit(r)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_DNIKeyTyped

    private void DomicilioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DomicilioKeyTyped
        char t = evt.getKeyChar();

        //Permitir teclas de control como Backspace, Delete, Enter, etc.
        if (Character.isISOControl(t)) {
            return;
        }

        String textoActual = Domicilio.getText();
        int longitud = textoActual.length();

        //Solo controlar repetición si es una letra
        if (Character.isLetter(t) && longitud >= 2) {
            char ultimo = textoActual.charAt(longitud - 1);
            char penultimo = textoActual.charAt(longitud - 2);

            if (ultimo == penultimo && penultimo == t) {
                getToolkit().beep();
                evt.consume(); // evita que se escriba
            }
        }
    }//GEN-LAST:event_DomicilioKeyTyped

    private void TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoKeyTyped
        char r = evt.getKeyChar();

        if (Character.isISOControl(r)) {
            return; // permite borrar, mover, etc.
        }

        //Solo permite letras, numeros y signos no
        if (!Character.isDigit(r)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_TelefonoKeyTyped

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        int filaSeleccionada = Tabla.getSelectedRow();
        if (filaSeleccionada != -1) {
            int opcion = JOptionPane.showConfirmDialog(
                    null,
                    "¿Deseás Eliminar?",
                    "Confirmar acción",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE
            );

            if (opcion == JOptionPane.OK_OPTION) {
                int fila = Tabla.getSelectedRow();
                int cod = Integer.parseInt(Tabla.getValueAt(fila, 0).toString());
                int borrado = 1;
                try {
                    CLASES.Empleados.EliminarEmpleados(con, cod, borrado);
                    JOptionPane.showMessageDialog(null, "Eliminao");
                    tabla1.setRowCount(0); // Limpia
                    CLASES.Empleados.MostrarEmpleados(con, tabla1);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "ERROR");
                }
            } else if (opcion == JOptionPane.CANCEL_OPTION || opcion == JOptionPane.CLOSED_OPTION) {
                // El usuario eligió "Cancelar" o cerró la ventana
                System.out.println("Cancelado");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila primero.");
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void NewCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCargoActionPerformed
        Cargar.setEnabled(!NewCargo.isSelected());
        Eliminar.setEnabled(!NewCargo.isSelected());
        Modificar.setEnabled(!NewCargo.isSelected());
        opcCargo.setEnabled(!NewCargo.isSelected());
        nuevocargo.setEnabled(NewCargo.isSelected());
        GuardarCargo.setEnabled(NewCargo.isSelected());
        area.setEnabled(NewCargo.isSelected());

        Menu.setEnabled(!NewCargo.isSelected());
        Movimiento.setEnabled(!NewCargo.isSelected());
        Asistencia.setEnabled(!NewCargo.isSelected());
        Empleados.setEnabled(!NewCargo.isSelected());
        Estadisticas.setEnabled(!NewCargo.isSelected());
        Ayuda.setEnabled(!NewCargo.isSelected());
        Configuracion.setEnabled(!NewCargo.isSelected());
        Salir.setEnabled(!NewCargo.isSelected());
    }//GEN-LAST:event_NewCargoActionPerformed

    private void GuardarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCargoActionPerformed
        String cargo = (nuevocargo.getText());
        String ar = (String) area.getSelectedItem();
        int borrado = 0;
        if (!cargo.trim().isEmpty() && !ar.equals("Area")) {
            try {
                CLASES.Empleados.AgregarCargo(con, cargo, ar, borrado);
                JOptionPane.showMessageDialog(null, "Cargao");

                NewCargo.setSelected(false);
                opcCargo.setEnabled(false);
                GuardarCargo.setEnabled(false);
                nuevocargo.setText("");
                tabla1.setRowCount(0);
                Cargar.setEnabled(true);
                Modificar.setEnabled(true);
                Eliminar.setEnabled(true);
                area.setEnabled(false);

                Menu.setEnabled(true);
                Movimiento.setEnabled(true);
                Asistencia.setEnabled(true);
                Empleados.setEnabled(true);
                Estadisticas.setEnabled(true);
                Ayuda.setEnabled(true);
                Configuracion.setEnabled(true);
                Salir.setEnabled(true);
                opcCargo.setEnabled(true);

                CLASES.Empleados.MostrarEmpleados(con, tabla1);
                refrescarCombo();
                Tabla.setModel(tabla1);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERROR13");
            }
        } else {
            JOptionPane.showMessageDialog(null, "¡HAY CAMPOS VACIOS! Por favor, revise");
        }
    }//GEN-LAST:event_GuardarCargoActionPerformed

    private void nuevocargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevocargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevocargoActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        x = 1;
        c = 1;
        int filaSeleccionada = Tabla.getSelectedRow();
        if (filaSeleccionada != -1) {
            int fila = Tabla.getSelectedRow();
            int cod = Integer.parseInt(Tabla.getValueAt(fila, 0).toString());
            id = Integer.parseInt(Tabla.getValueAt(fila, 0).toString());
            Guardar.setEnabled(true);
            try {
                CLASES.Empleados.SacarEmpleados(con, cod, Nombre, Apellido, DNI, Domicilio, Email, Telefono, Fecha, GS, Cargo);
                Nombre.setEnabled(true);
                Apellido.setEnabled(true);
                DNI.setEnabled(true);
                Domicilio.setEnabled(true);
                Email.setEnabled(true);
                Telefono.setEnabled(true);
                Fecha.setEnabled(true);
                Cargar.setText("Cancelar");
                Limpiar.setEnabled(true);
                Guardar.setEnabled(true);
                GS.setEnabled(true);
                Cargo.setEnabled(true);
                NewCargo.setEnabled(false);
                opcCargo.setEnabled(false);
                Eliminar.setEnabled(false);

                Menu.setEnabled(false);
                Movimiento.setEnabled(false);
                Asistencia.setEnabled(false);
                Empleados.setEnabled(false);
                Estadisticas.setEnabled(false);
                Ayuda.setEnabled(false);
                Configuracion.setEnabled(false);
                Salir.setEnabled(false);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "ERROR" + ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila primero.");

        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void opcCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcCargoActionPerformed
        String seleccion = (String) opcCargo.getSelectedItem();

        switch (seleccion) {
            case "Modificar":
                // Abrís ventana de modificación
                ModElimCargo ventana = new ModElimCargo(1, this);
                ventana.setVisible(true);
                break;

            case "Eliminar":
                // Abrís ventana de eliminación
                ModElimCargo ventana2 = new ModElimCargo(0, this);
                ventana2.setVisible(true);
                break;
        }

        opcCargo.setSelectedIndex(0);
    }//GEN-LAST:event_opcCargoActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido;
    private javax.swing.JButton Asistencia;
    private javax.swing.JMenuItem Asistencia2;
    private javax.swing.JButton Ayuda;
    private javax.swing.JMenuItem Ayuda2;
    private javax.swing.JButton Cargar;
    private javax.swing.JComboBox<String> Cargo;
    private javax.swing.JButton Configuracion;
    private javax.swing.JMenuItem Configuracion2;
    private javax.swing.JTextField DNI;
    private javax.swing.JTextField Domicilio;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField Email;
    private javax.swing.JButton Empleados;
    private javax.swing.JMenuItem Empleados2;
    private javax.swing.JButton Estadisticas;
    private javax.swing.JMenuItem Estadisticas2;
    private com.toedter.calendar.JDateChooser Fecha;
    private javax.swing.JComboBox<String> GS;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton GuardarCargo;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Menu;
    private javax.swing.JMenuItem Menu2;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton Movimiento;
    private javax.swing.JMenuItem Movimientos;
    private javax.swing.JCheckBox NewCargo;
    private javax.swing.JTextField Nombre;
    private javax.swing.JMenu Opciones2;
    private javax.swing.JButton Salir;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextField Telefono;
    private javax.swing.JComboBox<String> area;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField nuevocargo;
    private javax.swing.JComboBox<String> opcCargo;
    // End of variables declaration//GEN-END:variables
}
