/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CLASES.Movimientos.Cliente;
import CLASES.Movimientos.Trip;
import CONEXIONES.Conexiones;

import java.awt.*;
import java.awt.event.*;
import java.awt.image.*;
import java.io.*;
import java.sql.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;

/**
 *
 * @author Facuymayriver
 */
public class Relevar extends javax.swing.JFrame {

    Connection con = Conexiones.Conexion();
    ResultSet rs;
    int idChofer, idMedico, idEnfermero, idvictor;
    static int idtrip;
    String fechaActual, veri;

    public class PanelDibujo extends JPanel {

        private BufferedImage imagen, imagenOriginal;

        public PanelDibujo(String ruta) throws IOException {

            Toolkit toolkit = Toolkit.getDefaultToolkit();
            Image cursorImg = toolkit.getImage(getClass().getResource("/IMAGENES/lapiz.png"));

            // 📍 Crear cursor
            Point hotspot = new Point(0, 0); // Donde está la punta del lápiz
            Cursor cursorPersonalizado = toolkit.createCustomCursor(cursorImg, hotspot, "Lapiz");

            // 🔁 Aplicar cursor al panel
            this.setCursor(cursorPersonalizado);

            imagen = ImageIO.read(
                    getClass().getResource(ruta)
            );

            imagenOriginal = ImageIO.read(getClass().getResource(ruta));

            addMouseMotionListener(new MouseMotionAdapter() {
                @Override
                public void mouseDragged(MouseEvent e) {
                    Graphics2D g2d = imagen.createGraphics();
                    g2d.setColor(Color.RED);
                    g2d.fillOval(e.getX(), e.getY(), 5, 5);
                    g2d.dispose();
                    repaint();
                }
            });
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            g.drawImage(imagen, 0, 0, (ImageObserver) this);
        }

        public void guardar(String ruta) throws IOException {
            ImageIO.write(imagen, "png", new File(ruta));
        }

        // Método para borrar (restaurar la imagen original)
        public void borrar() {
            imagen = new BufferedImage(imagenOriginal.getWidth(), imagenOriginal.getHeight(), imagenOriginal.getType());
            Graphics2D g2d = imagen.createGraphics();
            g2d.drawImage(imagenOriginal, 0, 0, null);
            g2d.dispose();
            repaint();
        }
    }

    public class PanelImagen extends JPanel {

        private final BufferedImage imagen2;

        public PanelImagen(String ruta) throws IOException {
            imagen2 = ImageIO.read(
                    getClass().getResource(ruta)
            );
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);

            if (imagen2 != null) {
                // Dibujar imagen ajustada al tamaño actual del panel
                g.drawImage(imagen2, 0, 0, getWidth(), getHeight(), this);
            }
        }
    }

    public Relevar(int idtrip) {
        this.idtrip = idtrip;
        
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(1570, 860);
        String vic = String.valueOf(idtrip);
        LocalDate hoy = LocalDate.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String fechaActual2 = hoy.format(formato);
        CLASES.Relevar.Relevo(con, Victor, anterior1, saliente1, entrante1, kmi1, kmf, turno, idtrip);
        Fecha1.setText(fechaActual2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jToggleButton5 = new javax.swing.JToggleButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jToggleButton6 = new javax.swing.JToggleButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jToggleButton7 = new javax.swing.JToggleButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jToggleButton8 = new javax.swing.JToggleButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jToggleButton9 = new javax.swing.JToggleButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jToggleButton10 = new javax.swing.JToggleButton();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jToggleButton11 = new javax.swing.JToggleButton();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jToggleButton12 = new javax.swing.JToggleButton();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jToggleButton13 = new javax.swing.JToggleButton();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jToggleButton14 = new javax.swing.JToggleButton();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jToggleButton15 = new javax.swing.JToggleButton();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jToggleButton16 = new javax.swing.JToggleButton();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jToggleButton17 = new javax.swing.JToggleButton();
        jLabel66 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        victor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        kmi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        anterior = new javax.swing.JLabel();
        jLabel173 = new javax.swing.JLabel();
        saliente = new javax.swing.JLabel();
        jLabel174 = new javax.swing.JLabel();
        jLabel175 = new javax.swing.JLabel();
        jLabel176 = new javax.swing.JLabel();
        entrante = new javax.swing.JLabel();
        Fondo = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel177 = new javax.swing.JLabel();
        Fecha1 = new javax.swing.JLabel();
        jLabel178 = new javax.swing.JLabel();
        jLabel179 = new javax.swing.JLabel();
        kmi1 = new javax.swing.JLabel();
        jLabel180 = new javax.swing.JLabel();
        kmf = new javax.swing.JLabel();
        jLabel182 = new javax.swing.JLabel();
        anterior1 = new javax.swing.JLabel();
        jLabel183 = new javax.swing.JLabel();
        saliente1 = new javax.swing.JLabel();
        jLabel184 = new javax.swing.JLabel();
        jLabel185 = new javax.swing.JLabel();
        turno = new javax.swing.JLabel();
        entrante1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Victor = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        try {
            Marca = new PanelImagen("/IMAGENES/Marca.png");
            jToggleButton33 = new javax.swing.JToggleButton();
            jToggleButton34 = new javax.swing.JToggleButton();
            jToggleButton35 = new javax.swing.JToggleButton();
            jToggleButton36 = new javax.swing.JToggleButton();
            jToggleButton37 = new javax.swing.JToggleButton();
            jToggleButton38 = new javax.swing.JToggleButton();
            jToggleButton39 = new javax.swing.JToggleButton();
            jToggleButton40 = new javax.swing.JToggleButton();
            jToggleButton41 = new javax.swing.JToggleButton();
            jLabel8 = new javax.swing.JLabel();
            jPanel4 = new javax.swing.JPanel();
            try {
                jPanel15 = new PanelImagen("/IMAGENES/marcanivel.png");
                jToggleButton42 = new javax.swing.JToggleButton();
                jToggleButton43 = new javax.swing.JToggleButton();
                jToggleButton44 = new javax.swing.JToggleButton();
                jTextField2 = new javax.swing.JTextField();
                jLabel16 = new javax.swing.JLabel();
                jLabel17 = new javax.swing.JLabel();
                jLabel18 = new javax.swing.JLabel();
                try {
                    jPanel12 = new PanelDibujo("/IMAGENES/nivel.png");
                    jLabel10 = new javax.swing.JLabel();
                    Borrar2 = new javax.swing.JButton();
                    jPanel6 = new javax.swing.JPanel();
                    jLabel9 = new javax.swing.JLabel();
                    try {
                        Ambulancia = new PanelDibujo("/IMAGENES/ambulancia.jpg");
                        Borrar = new javax.swing.JButton();
                        jPanel7 = new javax.swing.JPanel();
                        jLabel1 = new javax.swing.JLabel();
                        jScrollPane1 = new javax.swing.JScrollPane();
                        jTextArea1 = new javax.swing.JTextArea();
                        jPanel8 = new javax.swing.JPanel();
                        jPanel11 = new javax.swing.JPanel();
                        jPanel13 = new javax.swing.JPanel();
                        jLabel11 = new javax.swing.JLabel();
                        jLabel12 = new javax.swing.JLabel();
                        jToggleButton1 = new javax.swing.JToggleButton();
                        jPanel14 = new javax.swing.JPanel();
                        jLabel13 = new javax.swing.JLabel();
                        jLabel14 = new javax.swing.JLabel();
                        jTextField1 = new javax.swing.JTextField();
                        jLabel15 = new javax.swing.JLabel();
                        jToggleButton2 = new javax.swing.JToggleButton();
                        try {
                            Funciona = new PanelImagen("/IMAGENES/Funciona.png");
                            jLabel67 = new javax.swing.JLabel();
                            jToggleButton18 = new javax.swing.JToggleButton();
                            jToggleButton19 = new javax.swing.JToggleButton();
                            jToggleButton20 = new javax.swing.JToggleButton();
                            jToggleButton21 = new javax.swing.JToggleButton();
                            jToggleButton22 = new javax.swing.JToggleButton();
                            jToggleButton23 = new javax.swing.JToggleButton();
                            jToggleButton24 = new javax.swing.JToggleButton();
                            jToggleButton25 = new javax.swing.JToggleButton();
                            jToggleButton26 = new javax.swing.JToggleButton();
                            jToggleButton27 = new javax.swing.JToggleButton();
                            jToggleButton28 = new javax.swing.JToggleButton();
                            jToggleButton29 = new javax.swing.JToggleButton();
                            jToggleButton30 = new javax.swing.JToggleButton();
                            jToggleButton31 = new javax.swing.JToggleButton();
                            jToggleButton32 = new javax.swing.JToggleButton();

                            jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                            jLabel21.setText("Funciona");

                            jLabel22.setText("Luz Posición");

                            jLabel23.setText("Luces Direccionales");

                            jLabel24.setText("Luces Altas");

                            jLabel25.setText("Luces Destelladoras de");

                            jLabel26.setText("SI");

                            jToggleButton3.setText("NO");

                            jLabel27.setText("No");

                            jLabel28.setText("SI");

                            jToggleButton4.setText("NO");

                            jLabel29.setText("No");

                            jLabel30.setText("SI");

                            jToggleButton5.setText("NO");

                            jLabel31.setText("No");

                            jLabel32.setText("SI");

                            jToggleButton6.setText("NO");

                            jLabel33.setText("No");

                            jLabel34.setText("Luces Bajas");

                            jLabel35.setText("Luces de Freno");

                            jLabel36.setText("Luces Traseras");

                            jLabel37.setText("Limpia Parabrisas");

                            jLabel38.setText("Frenos");

                            jLabel39.setText("No");

                            jToggleButton7.setText("NO");

                            jLabel40.setText("SI");

                            jLabel41.setText("No");

                            jToggleButton8.setText("NO");

                            jLabel42.setText("SI");

                            jLabel43.setText("No");

                            jToggleButton9.setText("NO");

                            jLabel44.setText("SI");

                            jLabel45.setText("No");

                            jToggleButton10.setText("NO");

                            jLabel46.setText("SI");

                            jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                            jLabel47.setText("Indicador de Temperatura Motor");

                            jLabel48.setText("Testigo de Service");

                            jLabel49.setText("Indicador de temperatura de combustiblw");

                            jLabel50.setText("Indicador de Nivel de Combustible");

                            jLabel51.setText("Carga Bateria");

                            jLabel52.setText("Calefactor y Aire Acondicionado");

                            jLabel53.setText("No");

                            jToggleButton11.setText("NO");

                            jLabel54.setText("SI");

                            jLabel55.setText("No");

                            jToggleButton12.setText("NO");

                            jLabel56.setText("SI");

                            jLabel57.setText("No");

                            jToggleButton13.setText("NO");

                            jLabel58.setText("SI");

                            jLabel59.setText("No");

                            jToggleButton14.setText("NO");

                            jLabel60.setText("SI");

                            jLabel61.setText("No");

                            jToggleButton15.setText("NO");

                            jLabel62.setText("SI");

                            jLabel63.setText("No");

                            jToggleButton16.setText("NO");

                            jLabel64.setText("SI");

                            jLabel65.setText("No");

                            jToggleButton17.setText("NO");

                            jLabel66.setText("SI");

                            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                            jPanel5.setLayout(jPanel5Layout);
                            jPanel5Layout.setHorizontalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel23)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel29)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(3, 3, 3)
                                            .addComponent(jLabel28))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel22)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel27)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(3, 3, 3)
                                            .addComponent(jLabel26))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel24)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel31)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(3, 3, 3)
                                            .addComponent(jLabel30))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel34)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel39)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(3, 3, 3)
                                            .addComponent(jLabel40))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel35)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel41)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(3, 3, 3)
                                            .addComponent(jLabel42))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel36)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel43)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(3, 3, 3)
                                            .addComponent(jLabel44))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel37)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel45)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jToggleButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(3, 3, 3)
                                            .addComponent(jLabel46))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel25)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                            .addComponent(jLabel33)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(3, 3, 3)
                                            .addComponent(jLabel32))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel51)
                                                .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel48)
                                                    .addComponent(jLabel38)
                                                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                    .addComponent(jLabel53)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jToggleButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(3, 3, 3)
                                                    .addComponent(jLabel54))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                    .addComponent(jLabel55)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jToggleButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(3, 3, 3)
                                                    .addComponent(jLabel56))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                    .addComponent(jLabel57)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jToggleButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(3, 3, 3)
                                                    .addComponent(jLabel58))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                    .addComponent(jLabel59)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jToggleButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(3, 3, 3)
                                                    .addComponent(jLabel60))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                    .addComponent(jLabel61)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jToggleButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(3, 3, 3)
                                                    .addComponent(jLabel62))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                    .addComponent(jLabel63)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(3, 3, 3)
                                                    .addComponent(jLabel64))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                    .addComponent(jLabel65)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jToggleButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(3, 3, 3)
                                                    .addComponent(jLabel66)))))
                                    .addContainerGap())
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(125, 125, 125)
                                    .addComponent(jLabel21)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            );
                            jPanel5Layout.setVerticalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel22)
                                        .addComponent(jToggleButton3)
                                        .addComponent(jLabel27)
                                        .addComponent(jLabel26))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel23)
                                        .addComponent(jToggleButton4)
                                        .addComponent(jLabel29)
                                        .addComponent(jLabel28))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel24)
                                        .addComponent(jToggleButton5)
                                        .addComponent(jLabel31)
                                        .addComponent(jLabel30))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel25)
                                        .addComponent(jToggleButton6)
                                        .addComponent(jLabel33)
                                        .addComponent(jLabel32))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel34)
                                        .addComponent(jToggleButton7)
                                        .addComponent(jLabel39)
                                        .addComponent(jLabel40))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel35)
                                        .addComponent(jToggleButton8)
                                        .addComponent(jLabel41)
                                        .addComponent(jLabel42))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel36)
                                        .addComponent(jToggleButton9)
                                        .addComponent(jLabel43)
                                        .addComponent(jLabel44))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel37)
                                        .addComponent(jToggleButton10)
                                        .addComponent(jLabel45)
                                        .addComponent(jLabel46))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jToggleButton11)
                                            .addComponent(jLabel53)
                                            .addComponent(jLabel54))
                                        .addComponent(jLabel38))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jToggleButton12)
                                            .addComponent(jLabel55)
                                            .addComponent(jLabel56))
                                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jToggleButton13)
                                            .addComponent(jLabel57)
                                            .addComponent(jLabel58))
                                        .addComponent(jLabel48))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jToggleButton14)
                                            .addComponent(jLabel59)
                                            .addComponent(jLabel60))
                                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jToggleButton15)
                                            .addComponent(jLabel61)
                                            .addComponent(jLabel62))
                                        .addComponent(jLabel50))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jToggleButton16)
                                            .addComponent(jLabel63)
                                            .addComponent(jLabel64))
                                        .addComponent(jLabel51))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jToggleButton17)
                                            .addComponent(jLabel65)
                                            .addComponent(jLabel66))
                                        .addComponent(jLabel52))
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            );

                            jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                            jLabel2.setText("Fecha:");
                            jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

                            Fecha.setText("jLabel3");
                            jPanel2.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 11, -1, -1));

                            jLabel3.setText("Victor");
                            jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, -1, -1));

                            jPanel2.add(victor, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 36, 133, -1));

                            jLabel4.setText("Kilometraje Inicial:");
                            jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 39, -1, -1));

                            kmi.setText("0");
                            jPanel2.add(kmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 39, 59, -1));

                            jLabel5.setText("Kilometraje final:");
                            jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 39, -1, -1));

                            jLabel6.setText("0");
                            jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 39, 64, -1));

                            jLabel7.setText("CVS Anterior:");
                            jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 74, -1, -1));

                            anterior.setText("-");
                            jPanel2.add(anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 74, 204, -1));

                            jLabel173.setText("CVS Saliente:");
                            jPanel2.add(jLabel173, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 74, -1, -1));

                            saliente.setText("-");
                            jPanel2.add(saliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 74, 196, -1));

                            jLabel174.setText("CVS Entrante:");
                            jPanel2.add(jLabel174, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 74, -1, -1));

                            jLabel175.setText("Turno:");
                            jPanel2.add(jLabel175, new org.netbeans.lib.awtextra.AbsoluteConstraints(909, 11, -1, -1));

                            jLabel176.setText("00:00hrs");
                            jPanel2.add(jLabel176, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 11, -1, -1));

                            entrante.setText("-");
                            jPanel2.add(entrante, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 74, 262, -1));

                            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                            setMaximumSize(new java.awt.Dimension(1550, 840));
                            setMinimumSize(new java.awt.Dimension(1550, 840));
                            setUndecorated(true);
                            setPreferredSize(new java.awt.Dimension(1550, 840));
                            setResizable(false);
                            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                            Fondo.setBackground(new java.awt.Color(204, 255, 204));
                            Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                            Fondo.setMinimumSize(new java.awt.Dimension(1550, 860));
                            Fondo.setPreferredSize(new java.awt.Dimension(1550, 860));
                            Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                            jPanel16.setBackground(new java.awt.Color(0, 0, 0));
                            jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                            jLabel177.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                            jLabel177.setForeground(new java.awt.Color(255, 255, 255));
                            jLabel177.setText(">Fecha:");
                            jPanel16.add(jLabel177, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

                            Fecha1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                            Fecha1.setForeground(new java.awt.Color(255, 255, 255));
                            Fecha1.setText("jLabel3");
                            jPanel16.add(Fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

                            jLabel178.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                            jLabel178.setForeground(new java.awt.Color(255, 255, 255));
                            jLabel178.setText(">Victor:");
                            jPanel16.add(jLabel178, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

                            jLabel179.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                            jLabel179.setForeground(new java.awt.Color(255, 255, 255));
                            jLabel179.setText(">Kilometraje Inicial:");
                            jPanel16.add(jLabel179, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

                            kmi1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                            kmi1.setForeground(new java.awt.Color(255, 255, 255));
                            kmi1.setText("0");
                            jPanel16.add(kmi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 59, -1));

                            jLabel180.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                            jLabel180.setForeground(new java.awt.Color(255, 255, 255));
                            jLabel180.setText(">Kilometraje final:");
                            jPanel16.add(jLabel180, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, 20));

                            kmf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                            kmf.setForeground(new java.awt.Color(255, 255, 255));
                            kmf.setText("0");
                            jPanel16.add(kmf, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 64, -1));

                            jLabel182.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                            jLabel182.setForeground(new java.awt.Color(255, 255, 255));
                            jLabel182.setText(">CVS Anterior:");
                            jPanel16.add(jLabel182, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

                            anterior1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                            anterior1.setForeground(new java.awt.Color(255, 255, 255));
                            anterior1.setText("-");
                            jPanel16.add(anterior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 560, -1));

                            jLabel183.setBackground(new java.awt.Color(255, 255, 255));
                            jLabel183.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                            jLabel183.setForeground(new java.awt.Color(255, 255, 255));
                            jLabel183.setText(">CVS Saliente:");
                            jPanel16.add(jLabel183, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));

                            saliente1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                            saliente1.setForeground(new java.awt.Color(255, 255, 255));
                            saliente1.setText("-");
                            jPanel16.add(saliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 580, -1));

                            jLabel184.setBackground(new java.awt.Color(255, 255, 255));
                            jLabel184.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                            jLabel184.setForeground(new java.awt.Color(255, 255, 255));
                            jLabel184.setText(">CVS Entrante:");
                            jPanel16.add(jLabel184, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

                            jLabel185.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                            jLabel185.setForeground(new java.awt.Color(255, 255, 255));
                            jLabel185.setText(">Turno:");
                            jPanel16.add(jLabel185, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

                            turno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                            turno.setForeground(new java.awt.Color(255, 255, 255));
                            turno.setText("00:00hrs");
                            jPanel16.add(turno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

                            entrante1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                            entrante1.setForeground(new java.awt.Color(255, 255, 255));
                            entrante1.setText("-");
                            jPanel16.add(entrante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 560, -1));

                            jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                            jLabel19.setForeground(new java.awt.Color(255, 51, 51));
                            jLabel19.setText("FICHA DE RELEVO DE MOVILES");
                            jPanel16.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

                            Victor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                            Victor.setForeground(new java.awt.Color(255, 255, 255));
                            Victor.setText("-");
                            jPanel16.add(Victor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 40, -1));

                            jButton2.setText("Todos si");
                            jPanel16.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 70, 90, -1));

                            jButton3.setText("Guardar");
                            jPanel16.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 10, -1, -1));

                            jButton1.setText("Todos no");
                            jPanel16.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 70, 90, -1));

                            jButton4.setText("Volver");
                            jButton4.addActionListener(new java.awt.event.ActionListener() {
                                public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jButton4ActionPerformed(evt);
                                }
                            });
                            jPanel16.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, -1, -1));

                            Fondo.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 11, 1520, 108));

                            jPanel3.setBackground(new java.awt.Color(0, 0, 0));
                            jPanel3.setMaximumSize(new java.awt.Dimension(600, 281));
                            jPanel3.setMinimumSize(new java.awt.Dimension(600, 281));
                            jPanel3.setPreferredSize(new java.awt.Dimension(600, 281));

                        } catch (IOException e) {
                            e.printStackTrace();
                            JOptionPane.showMessageDialog(this, "No se pudo cargar la imagen", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                        Marca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        Marca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                        jToggleButton33.setText("NO");
                        Marca.add(jToggleButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 10, 70, -1));

                        jToggleButton34.setText("NO");
                        Marca.add(jToggleButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 70, 70, -1));

                        jToggleButton35.setText("NO");
                        Marca.add(jToggleButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 130, 70, -1));

                        jToggleButton36.setText("NO");
                        Marca.add(jToggleButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 190, 70, -1));

                        jToggleButton37.setText("NO");
                        Marca.add(jToggleButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 10, 70, -1));

                        jToggleButton38.setText("NO");
                        Marca.add(jToggleButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 70, 70, -1));

                        jToggleButton39.setText("NO");
                        Marca.add(jToggleButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 60, -1));

                        jToggleButton40.setText("NO");
                        Marca.add(jToggleButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 70, -1));

                        jToggleButton41.setText("NO");
                        Marca.add(jToggleButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 140, 70, -1));

                        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
                        jLabel8.setText(">MARCAR (Extravio, deterioro, pérdida o mal funcionamiento)");

                        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                        jPanel3.setLayout(jPanel3Layout);
                        jPanel3Layout.setHorizontalGroup(
                            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addContainerGap(16, Short.MAX_VALUE))
                        );
                        jPanel3Layout.setVerticalGroup(
                            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        );

                        Fondo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, -1, 280));

                        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
                        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                    } catch (IOException e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(this, "No se pudo cargar la imagen", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                    jToggleButton42.setText("No");

                    jToggleButton43.setText("No");

                    jToggleButton44.setText("No");

                    jLabel16.setText("Nº Serie:");

                    jLabel17.setText("Cantidad");

                    jLabel18.setText("jLabel18");

                    javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
                    jPanel15.setLayout(jPanel15Layout);
                    jPanel15Layout.setHorizontalGroup(
                        jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel15Layout.createSequentialGroup()
                            .addGap(251, 251, 251)
                            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jToggleButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jToggleButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel15Layout.createSequentialGroup()
                                    .addGap(93, 93, 93)
                                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel15Layout.createSequentialGroup()
                                            .addComponent(jLabel17)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel15Layout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel18)))
                                    .addContainerGap(13, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jToggleButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32))))
                    );
                    jPanel15Layout.setVerticalGroup(
                        jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel15Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jToggleButton42)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jToggleButton43)
                                .addComponent(jToggleButton44))
                            .addContainerGap())
                        .addGroup(jPanel15Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(14, 14, 14)
                            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(jLabel18))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    );

                    jPanel4.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, 580, -1));

                } catch (IOException e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "No se pudo cargar la imagen", "Error", JOptionPane.ERROR_MESSAGE);
                }
                jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
                jPanel12.setLayout(jPanel12Layout);
                jPanel12Layout.setHorizontalGroup(
                    jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 578, Short.MAX_VALUE)
                );
                jPanel12Layout.setVerticalGroup(
                    jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 118, Short.MAX_VALUE)
                );

                jPanel4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, -1, -1));

                jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel10.setForeground(new java.awt.Color(255, 255, 255));
                jLabel10.setText(">MARCAR (Nivel)");
                jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

                Borrar2.setText("Borrar");
                Borrar2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Borrar2ActionPerformed(evt);
                    }
                });
                jPanel4.add(Borrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 90, -1));

                Fondo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 260, 600, 290));

                jPanel6.setBackground(new java.awt.Color(0, 0, 0));
                jPanel6.setMaximumSize(new java.awt.Dimension(600, 420));
                jPanel6.setMinimumSize(new java.awt.Dimension(600, 420));
                jPanel6.setPreferredSize(new java.awt.Dimension(600, 420));
                jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel9.setForeground(new java.awt.Color(255, 255, 255));
                jLabel9.setText(">MARCAR (Abolladuras, toques, rallones, etc.)");
                jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "No se pudo cargar la imagen", "Error", JOptionPane.ERROR_MESSAGE);
            }
            Ambulancia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout AmbulanciaLayout = new javax.swing.GroupLayout(Ambulancia);
            Ambulancia.setLayout(AmbulanciaLayout);
            AmbulanciaLayout.setHorizontalGroup(
                AmbulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE)
            );
            AmbulanciaLayout.setVerticalGroup(
                AmbulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE)
            );

            jPanel6.add(Ambulancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 44, 580, 360));

            Borrar.setText("Borrar");
            Borrar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BorrarActionPerformed(evt);
                }
            });
            jPanel6.add(Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 90, -1));

            Fondo.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 600, 420));

            jPanel7.setBackground(new java.awt.Color(0, 0, 0));

            jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(255, 255, 255));
            jLabel1.setText(">Observaciones");

            jTextArea1.setColumns(20);
            jTextArea1.setRows(5);
            jScrollPane1.setViewportView(jTextArea1);

            javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
            jPanel7.setLayout(jPanel7Layout);
            jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
                    .addContainerGap())
            );
            jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addContainerGap())
            );

            Fondo.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 560, 600, 280));

            jPanel8.setBackground(new java.awt.Color(0, 0, 0));
            jPanel8.setMaximumSize(new java.awt.Dimension(600, 122));
            jPanel8.setMinimumSize(new java.awt.Dimension(600, 122));
            jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jPanel11.setBackground(new java.awt.Color(255, 255, 255));
            jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            jPanel8.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 100));

            jPanel13.setBackground(new java.awt.Color(255, 255, 255));

            jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jLabel11.setText("LAVADERO");

            jLabel12.setText("Lavado Unidad");

            jToggleButton1.setText("NO");

            javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
            jPanel13.setLayout(jPanel13Layout);
            jPanel13Layout.setHorizontalGroup(
                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addGap(105, 105, 105))
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel12)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );
            jPanel13Layout.setVerticalGroup(
                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel11)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton1)
                        .addComponent(jLabel12))
                    .addContainerGap(33, Short.MAX_VALUE))
            );

            jPanel8.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 100));

            jPanel14.setBackground(new java.awt.Color(255, 255, 255));

            jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel13.setText("YPF RUTA");

            jLabel14.setText("Nº Tarjeta");

            jLabel15.setText("Entrega a Guarda Siguiente:");

            jToggleButton2.setText("NO");

            javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
            jPanel14.setLayout(jPanel14Layout);
            jPanel14Layout.setHorizontalGroup(
                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(104, 104, 104))
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel14Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField1))
                        .addGroup(jPanel14Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                            .addComponent(jToggleButton2)))
                    .addContainerGap())
            );
            jPanel14Layout.setVerticalGroup(
                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jToggleButton2))
                    .addContainerGap(12, Short.MAX_VALUE))
            );

            jPanel8.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 280, 100));

            Fondo.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 130, 600, 120));

        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "No se pudo cargar la imagen", "Error", JOptionPane.ERROR_MESSAGE);
        }
        Funciona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Funciona.setMaximumSize(new java.awt.Dimension(304, 720));
        Funciona.setMinimumSize(new java.awt.Dimension(304, 720));
        Funciona.setPreferredSize(new java.awt.Dimension(304, 720));
        Funciona.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel67.setText("Funciona");
        Funciona.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 1, -1, 20));

        jToggleButton18.setText("NO");
        Funciona.add(jToggleButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 89, -1));

        jToggleButton19.setText("NO");
        Funciona.add(jToggleButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 89, -1));

        jToggleButton20.setText("NO");
        Funciona.add(jToggleButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 89, -1));

        jToggleButton21.setText("NO");
        Funciona.add(jToggleButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 89, -1));

        jToggleButton22.setText("NO");
        Funciona.add(jToggleButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 89, -1));

        jToggleButton23.setText("NO");
        Funciona.add(jToggleButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 89, -1));

        jToggleButton24.setText("NO");
        Funciona.add(jToggleButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 89, -1));

        jToggleButton25.setText("NO");
        Funciona.add(jToggleButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 89, -1));

        jToggleButton26.setText("NO");
        Funciona.add(jToggleButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 89, -1));

        jToggleButton27.setText("NO");
        Funciona.add(jToggleButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 89, -1));

        jToggleButton28.setText("NO");
        Funciona.add(jToggleButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 89, -1));

        jToggleButton29.setText("NO");
        Funciona.add(jToggleButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 89, -1));

        jToggleButton30.setText("NO");
        Funciona.add(jToggleButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 89, -1));

        jToggleButton31.setText("NO");
        Funciona.add(jToggleButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 630, 89, -1));

        jToggleButton32.setText("NO");
        Funciona.add(jToggleButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 670, 89, -1));

        Fondo.add(Funciona, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 710));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1570, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Borrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Borrar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Borrar2ActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed

    }//GEN-LAST:event_BorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relevar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relevar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relevar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relevar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relevar(idtrip).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Ambulancia;
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Borrar2;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Fecha1;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Funciona;
    private javax.swing.JPanel Marca;
    private javax.swing.JLabel Victor;
    private javax.swing.JLabel anterior;
    private javax.swing.JLabel anterior1;
    private javax.swing.JLabel entrante;
    private javax.swing.JLabel entrante1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel173;
    private javax.swing.JLabel jLabel174;
    private javax.swing.JLabel jLabel175;
    private javax.swing.JLabel jLabel176;
    private javax.swing.JLabel jLabel177;
    private javax.swing.JLabel jLabel178;
    private javax.swing.JLabel jLabel179;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel180;
    private javax.swing.JLabel jLabel182;
    private javax.swing.JLabel jLabel183;
    private javax.swing.JLabel jLabel184;
    private javax.swing.JLabel jLabel185;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton jToggleButton27;
    private javax.swing.JToggleButton jToggleButton28;
    private javax.swing.JToggleButton jToggleButton29;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton30;
    private javax.swing.JToggleButton jToggleButton31;
    private javax.swing.JToggleButton jToggleButton32;
    private javax.swing.JToggleButton jToggleButton33;
    private javax.swing.JToggleButton jToggleButton34;
    private javax.swing.JToggleButton jToggleButton35;
    private javax.swing.JToggleButton jToggleButton36;
    private javax.swing.JToggleButton jToggleButton37;
    private javax.swing.JToggleButton jToggleButton38;
    private javax.swing.JToggleButton jToggleButton39;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton40;
    private javax.swing.JToggleButton jToggleButton41;
    private javax.swing.JToggleButton jToggleButton42;
    private javax.swing.JToggleButton jToggleButton43;
    private javax.swing.JToggleButton jToggleButton44;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JLabel kmf;
    private javax.swing.JLabel kmi;
    private javax.swing.JLabel kmi1;
    private javax.swing.JLabel saliente;
    private javax.swing.JLabel saliente1;
    private javax.swing.JLabel turno;
    private javax.swing.JComboBox<Cliente> victor;
    // End of variables declaration//GEN-END:variables
}
